/*
 * BooleanExtendedPage.java
 *
 * Created on May 20, 2013, 12:42 PM
 */

package com.rameses.beaninfo.editor.table;

import com.rameses.rcp.common.CheckBoxColumnHandler;
import com.rameses.rcp.common.Column;
import com.rameses.rcp.swingx.ComboItem;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;

/**
 *
 * @author  wflores
 */
public class CheckExtendedPage extends javax.swing.JPanel implements IExtendedPage
{
    private CheckBoxColumnHandler typeHandler;
     
    public CheckExtendedPage() 
    {
        initComponents();
        
        cboValueType.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent e) {
                onvalueTypeChanged(e);
            }
        });
    }
    
    public Column.TypeHandler getTypeHandler() { return typeHandler; }
    public void setTypeHandler(Column.TypeHandler typeHandler) 
    {
        this.typeHandler = new CheckBoxColumnHandler();
        if (typeHandler instanceof CheckBoxColumnHandler)
        {
            CheckBoxColumnHandler old = (CheckBoxColumnHandler) typeHandler;
            this.typeHandler.setValueType(old.getValueType()); 
            this.typeHandler.setCheckValue(old.getCheckValue()); 
            this.typeHandler.setUncheckValue(old.getUncheckValue()); 
        }
    } 
    
    private void onvalueTypeChanged(ItemEvent e)
    {
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cboValueType = new com.rameses.rcp.swingx.ComboField();
        txtCheckValue = new com.rameses.rcp.swingx.TextField();
        txtUncheckValue = new com.rameses.rcp.swingx.TextField();

        jLabel1.setText("Checked Value:");

        jLabel2.setText("Unchecked Value:");

        jLabel3.setText("Value Type:");

        cboValueType.setItems(new ComboItem[]{
            new ComboItem("Boolean", Boolean.class),
            new ComboItem("Integer", Integer.class),
            new ComboItem("String", String.class),
            new ComboItem("Object", Object.class)
        });
        cboValueType.setName("valueType");

        txtCheckValue.setName("checkValue");

        txtUncheckValue.setName("uncheckValue");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(31, 31, 31)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(4, 4, 4)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(txtUncheckValue, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(txtCheckValue, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(cboValueType, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(cboValueType, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(5, 5, 5)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(txtCheckValue, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(txtUncheckValue, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents



    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.swingx.ComboField cboValueType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private com.rameses.rcp.swingx.TextField txtCheckValue;
    private com.rameses.rcp.swingx.TextField txtUncheckValue;
    // End of variables declaration//GEN-END:variables
    
}
