/*
 * IntegerExtendedPage.java
 *
 * Created on May 20, 2013, 12:42 PM
 */

package com.rameses.beaninfo.editor.table;

import com.rameses.rcp.common.Column;
import com.rameses.rcp.common.IntegerColumnHandler;
import com.rameses.rcp.swingx.TextField;

/**
 *
 * @author  wflores
 */
public class IntegerExtendedPage extends javax.swing.JPanel implements IExtendedPage
{
    private IntegerColumnHandler typeHandler;
    
    public IntegerExtendedPage() {
        initComponents();
    }
        
    public Column.TypeHandler getTypeHandler() { return typeHandler; }
    public void setTypeHandler(Column.TypeHandler typeHandler) 
    {
        this.typeHandler = new IntegerColumnHandler();
        if (typeHandler instanceof IntegerColumnHandler)
        {
            IntegerColumnHandler old = (IntegerColumnHandler) typeHandler;
            this.typeHandler.setFormat(old.getFormat());
            this.typeHandler.setMinValue(old.getMinValue());
            this.typeHandler.setMaxValue(old.getMaxValue()); 
        }
    }     
      
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        textField1 = new com.rameses.rcp.swingx.TextField();

        jLabel1.setText("Format:");

        textField1.setName("format");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(28, 28, 28)
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 63, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(textField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(textField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private com.rameses.rcp.swingx.TextField textField1;
    // End of variables declaration//GEN-END:variables
    
}
