/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.rcp.draw.views;


public class AttributePicker extends javax.swing.JPanel {

    /**
     * Creates new form ColorPicker
     */
    public AttributePicker() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        attributePickerComponent1 = new com.rameses.rcp.draw.components.AttributePickerComponent();

        setLayout(new java.awt.BorderLayout());

        attributePickerComponent1.setHandler("handler");
        add(attributePickerComponent1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.draw.components.AttributePickerComponent attributePickerComponent1;
    // End of variables declaration//GEN-END:variables

}
