/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.rcp.draw.views;


public class FontPicker extends javax.swing.JPanel{

    /**
     * Creates new form FontPicker
     */
    public FontPicker() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fontPickerComponent1 = new com.rameses.rcp.draw.components.FontPickerComponent();

        setLayout(new java.awt.BorderLayout());

        fontPickerComponent1.setHandler("handler");
        add(fontPickerComponent1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.draw.components.FontPickerComponent fontPickerComponent1;
    // End of variables declaration//GEN-END:variables
}
