/*
 * ChangePwdPage.java
 *
 * Created on September 24, 2010, 5:04 PM
 */

package system.user.ui;

/**
 *
 * @author  ms
 */
public class ChangePwdPage extends javax.swing.JPanel {
    
    /** Creates new form ChangePwdPage */
    public ChangePwdPage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        formPanel1 = new com.rameses.rcp.util.FormPanel();
        xPasswordField3 = new com.rameses.rcp.control.XPasswordField();
        xPasswordField1 = new com.rameses.rcp.control.XPasswordField();
        xPasswordField2 = new com.rameses.rcp.control.XPasswordField();
        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();
        xPanel1 = new com.rameses.rcp.control.XPanel();
        xButton1 = new com.rameses.rcp.control.XButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 0), new java.awt.Dimension(5, 32767));
        xButton2 = new com.rameses.rcp.control.XButton();

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        jPanel2.setLayout(new com.rameses.rcp.control.layout.YLayout());

        formPanel1.setCaptionVAlignment(com.rameses.rcp.constant.UIConstants.CENTER);
        formPanel1.setCaptionWidth(130);
        formPanel1.setPadding(new java.awt.Insets(0, 0, 0, 0));

        xPasswordField3.setCaption("Old Password");
        xPasswordField3.setName("oldpwd"); // NOI18N
        xPasswordField3.setText("xPasswordField1");
        xPasswordField3.setPreferredSize(new java.awt.Dimension(0, 24));
        xPasswordField3.setRequired(true);
        formPanel1.add(xPasswordField3);

        xPasswordField1.setCaption("New Password");
        xPasswordField1.setName("newpwd"); // NOI18N
        xPasswordField1.setText("xPasswordField1");
        xPasswordField1.setPreferredSize(new java.awt.Dimension(0, 24));
        xPasswordField1.setRequired(true);
        formPanel1.add(xPasswordField1);

        xPasswordField2.setCaption("Confirm Password");
        xPasswordField2.setName("confirmpwd"); // NOI18N
        xPasswordField2.setText("xPasswordField1");
        xPasswordField2.setPreferredSize(new java.awt.Dimension(0, 24));
        xPasswordField2.setRequired(true);
        formPanel1.add(xPasswordField2);

        xFormPanel1.setCaptionVAlignment(com.rameses.rcp.constant.UIConstants.CENTER);
        xFormPanel1.setCaptionWidth(0);
        xFormPanel1.setCellpadding(new java.awt.Insets(0, 130, 0, 0));
        xFormPanel1.setOrientation(com.rameses.rcp.constant.UIConstants.HORIZONTAL);
        xFormPanel1.setPadding(new java.awt.Insets(0, 0, 0, 0));
        xFormPanel1.setShowCaption(false);
        formPanel1.add(xFormPanel1);

        xPanel1.setCellPadding(new java.awt.Insets(20, 130, 0, 0));
        xPanel1.setShowCaption(false);
        xPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        xButton1.setMnemonic('K');
        xButton1.setName("changePwd"); // NOI18N
        xButton1.setDefaultCommand(true);
        xButton1.setMargin(new java.awt.Insets(5, 14, 5, 14));
        xButton1.setShowCaption(false);
        xButton1.setText("  OK  ");
        xPanel1.add(xButton1);
        xPanel1.add(filler1);

        xButton2.setMnemonic('C');
        xButton2.setName("_close"); // NOI18N
        xButton2.setCellPadding(new java.awt.Insets(0, 10, 0, 0));
        xButton2.setImmediate(true);
        xButton2.setMargin(new java.awt.Insets(5, 14, 5, 14));
        xButton2.setShowCaption(false);
        xButton2.setText("Cancel");
        xPanel1.add(xButton2);

        formPanel1.add(xPanel1);

        jPanel2.add(formPanel1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private com.rameses.rcp.util.FormPanel formPanel1;
    private javax.swing.JPanel jPanel2;
    private com.rameses.rcp.control.XButton xButton1;
    private com.rameses.rcp.control.XButton xButton2;
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    private com.rameses.rcp.control.XPanel xPanel1;
    private com.rameses.rcp.control.XPasswordField xPasswordField1;
    private com.rameses.rcp.control.XPasswordField xPasswordField2;
    private com.rameses.rcp.control.XPasswordField xPasswordField3;
    // End of variables declaration//GEN-END:variables
    
}
