package system.user.ui;

public class ChangePwdOnLoginPage extends javax.swing.JPanel {
    
    /** Creates new form LoginPage */
    public ChangePwdOnLoginPage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        xLabel1 = new com.rameses.rcp.control.XLabel();
        jLabel2 = new javax.swing.JLabel();
        formPanel1 = new com.rameses.rcp.util.FormPanel();
        xPasswordField1 = new com.rameses.rcp.control.XPasswordField();
        xPasswordField2 = new com.rameses.rcp.control.XPasswordField();
        xButton1 = new com.rameses.rcp.control.XButton();

        setOpaque(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 0, 0));
        jPanel1.setLayout(new com.rameses.rcp.control.layout.YLayout());

        xLabel1.setExpression("Change Password ");
        xLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        xLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 25, 0));
        xLabel1.setFontStyle("font-size:18;");
        xLabel1.setUseHtml(true);
        jPanel1.add(xLabel1);

        jLabel2.setText("<html>Please change your current password.</html>");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 20, 0));
        jPanel1.add(jLabel2);

        formPanel1.setCaptionVAlignment(com.rameses.rcp.constant.UIConstants.CENTER);
        formPanel1.setCaptionWidth(120);

        xPasswordField1.setText("xPasswordField1");
        xPasswordField1.setCaption("New Password");
        xPasswordField1.setName("newpwd"); // NOI18N
        xPasswordField1.setPreferredSize(new java.awt.Dimension(200, 24));
        xPasswordField1.setRequired(true);
        formPanel1.add(xPasswordField1);

        xPasswordField2.setText("xPasswordField1");
        xPasswordField2.setCaption("Confirm Password");
        xPasswordField2.setName("confirmpwd"); // NOI18N
        xPasswordField2.setPreferredSize(new java.awt.Dimension(200, 24));
        xPasswordField2.setRequired(true);
        formPanel1.add(xPasswordField2);

        xButton1.setMnemonic('C');
        xButton1.setName("changePwd"); // NOI18N
        xButton1.setCellPadding(new java.awt.Insets(20, 120, 0, 0));
        xButton1.setDefaultCommand(true);
        xButton1.setMargin(new java.awt.Insets(5, 14, 5, 14));
        xButton1.setShowCaption(false);
        xButton1.setText("Change Password");
        formPanel1.add(xButton1);

        jPanel1.add(formPanel1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 417, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.util.FormPanel formPanel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private com.rameses.rcp.control.XButton xButton1;
    private com.rameses.rcp.control.XLabel xLabel1;
    private com.rameses.rcp.control.XPasswordField xPasswordField1;
    private com.rameses.rcp.control.XPasswordField xPasswordField2;
    // End of variables declaration//GEN-END:variables
    
}
