/*
 * RegistrationInitPage.java
 *
 * Created on September 25, 2010, 9:06 AM
 */

package system.registration.ui;

/**
 *
 * @author  ms
 */
public class NewTerminalRegistrationPage extends javax.swing.JPanel {
    
    /** Creates new form RegistrationInitPage */
    public NewTerminalRegistrationPage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        xLabel1 = new com.rameses.rcp.control.XLabel();
        jLabel2 = new javax.swing.JLabel();
        formPanel1 = new com.rameses.rcp.util.FormPanel();
        xTextField1 = new com.rameses.rcp.control.XTextField();
        xTextField3 = new com.rameses.rcp.control.XTextField();
        xPanel1 = new com.rameses.rcp.control.XPanel();
        xButton2 = new com.rameses.rcp.control.XButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 0), new java.awt.Dimension(10, 32767));
        xButton1 = new com.rameses.rcp.control.XButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(40, 40, 20, 20));
        jPanel1.setLayout(new com.rameses.rcp.control.layout.YLayout());

        xLabel1.setExpression("New Terminal Registration");
        xLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        xLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 25, 0));
        xLabel1.setFontStyle("font-size:18;");
        xLabel1.setUseHtml(true);
        jPanel1.add(xLabel1);

        jLabel2.setText("<html>Please fill in the information below. Contact helpdesk for assistance</html>");
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 20, 0));
        jPanel1.add(jLabel2);

        formPanel1.setCaptionVAlignment(com.rameses.rcp.constant.UIConstants.CENTER);
        formPanel1.setCaptionWidth(120);

        xTextField1.setCaption("Terminal Key");
        xTextField1.setName("terminalkey"); // NOI18N
        xTextField1.setIndex(-100);
        xTextField1.setPreferredSize(new java.awt.Dimension(200, 24));
        xTextField1.setRequired(true);
        formPanel1.add(xTextField1);

        xTextField3.setCaption("Registered By");
        xTextField3.setName("name"); // NOI18N
        xTextField3.setPreferredSize(new java.awt.Dimension(200, 24));
        xTextField3.setRequired(true);
        formPanel1.add(xTextField3);

        xPanel1.setCaption(" ");
        xPanel1.setCellPadding(new java.awt.Insets(20, 0, 40, 0));
        xPanel1.setPreferredSize(new java.awt.Dimension(200, 100));
        xPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 0, 0));

        xButton2.setMnemonic('B');
        xButton2.setName("_default"); // NOI18N
        xButton2.setImmediate(true);
        xButton2.setMargin(new java.awt.Insets(5, 14, 5, 14));
        xButton2.setText("  Back  ");
        xPanel1.add(xButton2);
        xPanel1.add(filler1);

        xButton1.setMnemonic('S');
        xButton1.setName("registerNew"); // NOI18N
        xButton1.setDefaultCommand(true);
        xButton1.setMargin(new java.awt.Insets(5, 14, 5, 14));
        xButton1.setText("Submit");
        xPanel1.add(xButton1);

        formPanel1.add(xPanel1);

        jPanel1.add(formPanel1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 473, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 367, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private com.rameses.rcp.util.FormPanel formPanel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private com.rameses.rcp.control.XButton xButton1;
    private com.rameses.rcp.control.XButton xButton2;
    private com.rameses.rcp.control.XLabel xLabel1;
    private com.rameses.rcp.control.XPanel xPanel1;
    private com.rameses.rcp.control.XTextField xTextField1;
    private com.rameses.rcp.control.XTextField xTextField3;
    // End of variables declaration//GEN-END:variables
    
}
