/*
 * RegistrationInitPage.java
 *
 * Created on September 25, 2010, 9:06 AM
 */

package system.registration.ui;

/**
 *
 * @author  ms
 */
public class RegistrationInitPage extends javax.swing.JPanel {
    
    /** Creates new form RegistrationInitPage */
    public RegistrationInitPage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        xLabel1 = new com.rameses.rcp.control.XLabel();
        jLabel2 = new javax.swing.JLabel();
        xRadio1 = new com.rameses.rcp.control.XRadio();
        xRadio2 = new com.rameses.rcp.control.XRadio();
        xPanel1 = new com.rameses.rcp.control.XPanel();
        xButton1 = new com.rameses.rcp.control.XButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(40, 40, 20, 20));
        jPanel1.setLayout(new com.rameses.rcp.control.layout.YLayout());

        xLabel1.setExpression("Registration");
        xLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        xLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 25, 0));
        xLabel1.setFontStyle("font-size:18;");
        xLabel1.setUseHtml(true);
        jPanel1.add(xLabel1);

        jLabel2.setText("<html>This machine is not yet registered.   Terminal registration is required for performing secured transactions.  Please choose a type of action below:</html>");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 20, 0));
        jPanel1.add(jLabel2);
        jLabel2.getAccessibleContext().setAccessibleName("<html>This machine is not yet registered.   Terminal registration is required for performing secured transactioons. Please choose a type of action below:</html>");

        buttonGroup1.add(xRadio1);
        xRadio1.setCaption("");
        xRadio1.setName("option"); // NOI18N
        xRadio1.setOptionValue(0);
        xRadio1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 20, 10, 0));
        xRadio1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        xRadio1.setText("  Register new terminal  ");
        xRadio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xRadio1ActionPerformed(evt);
            }
        });
        jPanel1.add(xRadio1);

        buttonGroup1.add(xRadio2);
        xRadio2.setCaption("");
        xRadio2.setName("option"); // NOI18N
        xRadio2.setOptionValue(1);
        xRadio2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 20, 10, 0));
        xRadio2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        xRadio2.setText("  Recover existing terminal  ");
        jPanel1.add(xRadio2);

        xPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 50, 0));
        xPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        xButton1.setMnemonic('N');
        xButton1.setName("next"); // NOI18N
        xButton1.setDefaultCommand(true);
        xButton1.setMargin(new java.awt.Insets(5, 14, 5, 14));
        xButton1.setText("  Next  ");
        xPanel1.add(xButton1);

        jPanel1.add(xPanel1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 545, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void xRadio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xRadio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xRadio1ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private com.rameses.rcp.control.XButton xButton1;
    private com.rameses.rcp.control.XLabel xLabel1;
    private com.rameses.rcp.control.XPanel xPanel1;
    private com.rameses.rcp.control.XRadio xRadio1;
    private com.rameses.rcp.control.XRadio xRadio2;
    // End of variables declaration//GEN-END:variables
    
}
