/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.menu.views;

/**
 *
 * @author elmonazareno
 */

public class FXHomeMenuPage extends javax.swing.JPanel {

    /**
     * Creates new form FXHomeMenuPage
     */
    public FXHomeMenuPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xImage1 = new com.rameses.rcp.control.XImage();
        xWebView1 = new com.rameses.rcp.control.XWebView();

        setLayout(new java.awt.BorderLayout());

        xImage1.setBackground(new java.awt.Color(255, 255, 255));
        com.rameses.rcp.control.border.XEtchedBorder xEtchedBorder1 = new com.rameses.rcp.control.border.XEtchedBorder();
        xEtchedBorder1.setHideLeft(true);
        xEtchedBorder1.setHideRight(true);
        xEtchedBorder1.setHideTop(true);
        xEtchedBorder1.setPadding(new java.awt.Insets(0, 10, 0, 0));
        xImage1.setBorder(xEtchedBorder1);
        xImage1.setHideWhenNoIcon(true);
        xImage1.setName("icon"); // NOI18N
        xImage1.setOpaque(true);
        xImage1.setPreferredSize(new java.awt.Dimension(46, 60));
        add(xImage1, java.awt.BorderLayout.NORTH);

        xWebView1.setBorder(null);
        xWebView1.setName("menuHtml"); // NOI18N
        add(xWebView1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.control.XImage xImage1;
    private com.rameses.rcp.control.XWebView xWebView1;
    // End of variables declaration//GEN-END:variables
}
