package com.rameses.rcp.draw.components;

import com.rameses.rcp.control.XComponentPanel;
import com.rameses.rcp.ui.annotations.ComponentBean;
import java.awt.Color;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

@ComponentBean("com.rameses.rcp.draw.components.ColorChooserComponentModel")
public class ColorChooserComponent extends XComponentPanel {
    private AttributePickerModel model;
    private String handler;
    
    /**
     * Creates new form ColorChooser
     */
    public ColorChooserComponent() {
        initComponents();
    }

    public String getHandler(){
        return handler;
    }
    
    public void setHandler(String handler){
        this.handler = handler;
    }
    
    @Override
    protected void initComponentBean(com.rameses.rcp.common.ComponentBean bean) {
        model = (AttributePickerModel) getProperty(getHandler());
        
        colorChooser.getSelectionModel().addChangeListener(new ChangeListener(){

            @Override
            public void stateChanged(ChangeEvent e) {
                if (model != null){
                    Color color = colorChooser.getColor();
                    model.getEditor().attributeChanged(model.getAttributeKey(), color);
                }
            }
        
        });
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        colorChooser = new javax.swing.JColorChooser();

        setLayout(new java.awt.BorderLayout());
        add(colorChooser, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JColorChooser colorChooser;
    // End of variables declaration//GEN-END:variables

    
}
