package com.rameses.rcp.draw.components;

import com.rameses.rcp.common.DrawModel;
import com.rameses.rcp.draw.DrawCanvas;
import com.rameses.rcp.control.XComponentPanel;
import com.rameses.rcp.ui.annotations.ComponentBean;
import com.rameses.rcp.draw.interfaces.Editor;
import java.awt.BorderLayout;
import java.awt.Dimension;
import javax.swing.JScrollPane;


@ComponentBean("com.rameses.rcp.draw.components.DrawComponentModel")
public class DrawComponent extends XComponentPanel {
    private String handler;
    private DrawModel model;
    private Editor editor;
    private DrawCanvas canvas;

    /**  * Creates new form DrawComponent
     */
    public DrawComponent() {
        initComponents();
        setFocusable(true);
        cboCategory.setFocusable(false);
        canvas = new DrawCanvas();
        JScrollPane scroller = new JScrollPane(canvas);
        scroller.setPreferredSize(new Dimension(200, 100));
        add(scroller, BorderLayout.CENTER);
    }
    
    
    public String getHandler(){
        return handler;
    }
    
    public void setHandler(String handler){
        this.handler = handler;
    }

    @Override
    protected void initComponentBean(com.rameses.rcp.common.ComponentBean bean) {
        editor = (Editor)bean.getProperty("editor");
        editor.setCanvas(canvas);
        canvas.setEditor(editor);
        model = (DrawModel) getProperty(getHandler());
        bean.setProperty("handler", model);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        cboCategory = new com.rameses.rcp.control.XComboBox();
        xActionBar3 = new com.rameses.rcp.control.XActionBar();
        xActionBar4 = new com.rameses.rcp.control.XActionBar();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 5, 1));
        jPanel1.setPreferredSize(new java.awt.Dimension(204, 32));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.BorderLayout());

        cboCategory.setAllowNull(false);
        cboCategory.setItems("categories");
        cboCategory.setName("category"); // NOI18N
        cboCategory.setPreferredSize(new java.awt.Dimension(68, 21));
        cboCategory.setVisibleWhen("#{showToolbars && showDrawTools}");
        jPanel3.add(cboCategory, java.awt.BorderLayout.WEST);

        xActionBar3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 5, 1, 1));
        xActionBar3.setDepends(new String[] {"category"});
        xActionBar3.setDynamic(true);
        xActionBar3.setName("drawTools"); // NOI18N
        xActionBar3.setVisibleWhen("#{showToolbars && showDrawTools}");
        jPanel3.add(xActionBar3, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        xActionBar4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        xActionBar4.setDynamic(true);
        xActionBar4.setName("editTools"); // NOI18N
        xActionBar4.setVisibleWhen("#{showToolbars && showEditTools}");
        jPanel1.add(xActionBar4, java.awt.BorderLayout.WEST);

        add(jPanel1, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.control.XComboBox cboCategory;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private com.rameses.rcp.control.XActionBar xActionBar3;
    private com.rameses.rcp.control.XActionBar xActionBar4;
    // End of variables declaration//GEN-END:variables




}
