/*
 * TaskForm.java
 *
 * Created on June 20, 2014, 3:23 PM
 */

package com.rameses.osiris2.common.ui;

import com.rameses.osiris2.themes.FormPage;
import com.rameses.rcp.ui.annotations.Template;

/**
 *
 * @author  Elmo
 */
@Template(FormPage.class)
public class TaskFormPage extends javax.swing.JPanel {
    
    /** Creates new form TaskForm */
    public TaskFormPage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        xHtmlView1 = new com.rameses.rcp.control.XHtmlView();

        setLayout(new java.awt.BorderLayout());

        xHtmlView1.setBackground(new java.awt.Color(255, 255, 204));
        xHtmlView1.setName("message");
        xHtmlView1.setVisibleWhen("#{message!=null}");
        add(xHtmlView1, java.awt.BorderLayout.NORTH);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.control.XHtmlView xHtmlView1;
    // End of variables declaration//GEN-END:variables
    
}
