/*
 * ExitPage.java
 *
 * Created on November 4, 2010, 4:23 PM
 */

package system.tools.ui;

/**
 *
 * @author  ms
 */
public class SystemExitPage extends javax.swing.JPanel {
    
    /** Creates new form ExitPage */
    public SystemExitPage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        xButton1 = new com.rameses.rcp.control.XButton();
        xButton2 = new com.rameses.rcp.control.XButton();
        xButton3 = new com.rameses.rcp.control.XButton();
        xButton4 = new com.rameses.rcp.control.XButton();
        jSeparator1 = new javax.swing.JSeparator();

        setPreferredSize(new java.awt.Dimension(418, 266));

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 0));

        xButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/images/shutdown.png"))); // NOI18N
        xButton1.setName("shutdown"); // NOI18N
        xButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
        xButton1.setFontStyle("font-size:14;");
        xButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        xButton1.setIconTextGap(20);
        xButton1.setMargin(new java.awt.Insets(5, 14, 5, 14));
        xButton1.setPreferredSize(new java.awt.Dimension(100, 93));
        xButton1.setText("Shutdown");
        xButton1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        xButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(xButton1);

        xButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/images/logoff.png"))); // NOI18N
        xButton2.setName("logoff"); // NOI18N
        xButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
        xButton2.setFontStyle("font-size:14;");
        xButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        xButton2.setIconTextGap(20);
        xButton2.setMargin(new java.awt.Insets(5, 14, 5, 14));
        xButton2.setPreferredSize(new java.awt.Dimension(100, 93));
        xButton2.setText("Log Off");
        xButton2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        xButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(xButton2);

        xButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/images/suspend.png"))); // NOI18N
        xButton3.setName("suspend"); // NOI18N
        xButton3.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 4, 4, 4));
        xButton3.setFontStyle("font-size:14;");
        xButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        xButton3.setIconTextGap(20);
        xButton3.setMargin(new java.awt.Insets(5, 14, 5, 14));
        xButton3.setPreferredSize(new java.awt.Dimension(100, 93));
        xButton3.setText("Suspend");
        xButton3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        xButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(xButton3);

        xButton4.setName("cancel"); // NOI18N
        xButton4.setMargin(new java.awt.Insets(5, 14, 5, 14));
        xButton4.setText("Cancel");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 411, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jSeparator1)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(xButton4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 88, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(xButton4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private com.rameses.rcp.control.XButton xButton1;
    private com.rameses.rcp.control.XButton xButton2;
    private com.rameses.rcp.control.XButton xButton3;
    private com.rameses.rcp.control.XButton xButton4;
    // End of variables declaration//GEN-END:variables
    
}
