/*
 * QueryFormPanel.java
 *
 * Created on April 24, 2013, 2:13 PM
 */

package com.rameses.osiris2.themes;

/**
 *
 * @author  compaq
 */
public class DefaultQueryFormPanel extends javax.swing.JPanel {
    
    /** Creates new form QueryFormPanel */
    public DefaultQueryFormPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        defaultLabel1 = new com.rameses.rcp.control.text.DefaultLabel();
        xActionTextField1 = new com.rameses.rcp.control.XActionTextField();
        xButton1 = new com.rameses.rcp.control.XButton();

        setLayout(new com.rameses.rcp.control.layout.XLayout());

        setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        setAlignmentX(0.1F);
        setAlignmentY(0.1F);
        defaultLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 5));
        defaultLabel1.setDisplayedMnemonic('s');
        defaultLabel1.setForeground(new java.awt.Color(80, 80, 80));
        defaultLabel1.setText("Search");
        defaultLabel1.setFontStyle("font-weight:bold;");
        defaultLabel1.setPreferredSize(new java.awt.Dimension(50, 14));
        add(defaultLabel1);

        xActionTextField1.setActionName("search");
        xActionTextField1.setCaption("Search");
        xActionTextField1.setFocusAccelerator('s');
        xActionTextField1.setFocusKeyStroke("F3");
        xActionTextField1.setName("query.searchtext");
        xActionTextField1.setPreferredSize(new java.awt.Dimension(220, 22));
        add(xActionTextField1);

        xButton1.setAccelerator("shift F3");
        xButton1.setIconResource("images/toolbars/filter.png");
        xButton1.setMargin(new java.awt.Insets(1, 1, 1, 1));
        xButton1.setName("advancedSearch");
        xButton1.setPreferredSize(new java.awt.Dimension(24, 22));
        xButton1.setVisibleWhen("#{allowAdvancedSearch == true}");
        add(xButton1);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.control.text.DefaultLabel defaultLabel1;
    private com.rameses.rcp.control.XActionTextField xActionTextField1;
    private com.rameses.rcp.control.XButton xButton1;
    // End of variables declaration//GEN-END:variables
    
}
