/*
 * EditorPanel.java
 *
 * Created on June 17, 2013, 3:30 PM
 */

package com.rameses.osiris2.themes;

/**
 *
 * @author  Elmo
 */
public class EditorPanel extends javax.swing.JPanel {
    
    /** Creates new form EditorPanel */
    public EditorPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        xButton1 = new com.rameses.rcp.control.XButton();
        xButton2 = new com.rameses.rcp.control.XButton();
        xLabel1 = new com.rameses.rcp.control.XLabel();

        setPreferredSize(new java.awt.Dimension(0, 25));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(43, 34));
        jPanel1.setLayout(null);

        xButton1.setBorder(null);
        xButton1.setText("...");
        xButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        xButton1.setName("edit"); // NOI18N
        jPanel1.add(xButton1);
        xButton1.setBounds(0, 0, 20, 20);

        xButton2.setBorder(null);
        xButton2.setText("X");
        xButton2.setFont(new java.awt.Font("Monospaced", 0, 11)); // NOI18N
        xButton2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        xButton2.setName("reset"); // NOI18N
        jPanel1.add(xButton2);
        xButton2.setBounds(20, 0, 20, 20);

        add(jPanel1, java.awt.BorderLayout.EAST);

        xLabel1.setBackground(new java.awt.Color(255, 255, 255));
        xLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        xLabel1.setExpression("#{value}");
        xLabel1.setOpaque(true);
        add(xLabel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private com.rameses.rcp.control.XButton xButton1;
    private com.rameses.rcp.control.XButton xButton2;
    private com.rameses.rcp.control.XLabel xLabel1;
    // End of variables declaration//GEN-END:variables
    
}
