/*
 * InboxDocBlankPage.java
 *
 * Created on August 25, 2013, 11:56 PM
 */

package com.rameses.osiris2.themes;

import com.rameses.rcp.control.border.XLineBorder;
import java.awt.Color;
import javax.swing.border.Border;

/**
 *
 * @author  wflores
 */
public class InboxDocBlankPage extends javax.swing.JPanel {
    
    public InboxDocBlankPage() {
        Color bgcolor = getBackground();        
        initComponents();
        Border border = getBorder();
        if (border instanceof XLineBorder && bgcolor != null) {
            XLineBorder lb = (XLineBorder)border;
            lb.setLineColor(bgcolor.darker()); 
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 279, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 169, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
