/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.osiris2.views;

import com.rameses.rcp.ui.annotations.StyleSheet;

/**
 *
 * @author wflores
 */
@StyleSheet 
public class SigIdDeviceListPage extends javax.swing.JPanel {

    /**
     * Creates new form SigIdDeviceListPage
     */
    public SigIdDeviceListPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xDataTable1 = new com.rameses.rcp.control.XDataTable();
        xPanel1 = new com.rameses.rcp.control.XPanel();
        xButton1 = new com.rameses.rcp.control.XButton();
        xButton2 = new com.rameses.rcp.control.XButton();

        setLayout(new java.awt.BorderLayout());

        xDataTable1.setHandler("listhandler");
        xDataTable1.setName("selectedItem"); // NOI18N
        add(xDataTable1, java.awt.BorderLayout.CENTER);

        xPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 5, 0));
        xPanel1.setLayout(new com.rameses.rcp.control.layout.XLayout());

        xButton1.setText("Set As Default");
        xButton1.setDepends(new String[] {"selectedItem"});
        xButton1.setDisableWhen("#{selectedItem == null}");
        xButton1.setName("setAsDefault"); // NOI18N
        xPanel1.add(xButton1);

        xButton2.setText("Test Device");
        xButton2.setDepends(new String[] {"selectedItem"});
        xButton2.setDisableWhen("#{selectedItem == null}");
        xButton2.setName("testDevice"); // NOI18N
        xPanel1.add(xButton2);

        add(xPanel1, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.control.XButton xButton1;
    private com.rameses.rcp.control.XButton xButton2;
    private com.rameses.rcp.control.XDataTable xDataTable1;
    private com.rameses.rcp.control.XPanel xPanel1;
    // End of variables declaration//GEN-END:variables
}
