/*
 * WaitPanel.java
 *
 * Created on November 5, 2013, 12:08 PM
 */

package com.rameses.osiris3.platform;

/**
 *
 * @author  wflores
 */
public class WaitPanel extends javax.swing.JPanel 
{
    public WaitPanel() {
        initComponents();
    }
    
    public void setMessage(String message) {
        lblmessage.setText("<html> <b style=\"font-size:14;\">"+message+"</b> </html>");
    }
    
    
    public final static WaitPanel create(String message) {
        WaitPanel wp = new WaitPanel();
        wp.setMessage(message);
        return wp; 
    }
    
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        lblmessage = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/rameses/osiris3/platform/icon/progressbar.gif")));
        add(jLabel1);
        jLabel1.setBounds(-135, 35, 375, 30);

        lblmessage.setForeground(new java.awt.Color(80, 80, 80));
        lblmessage.setText("<html> <b style=\"font-size:14;\">Logging off...</b> </html>");
        add(lblmessage);
        lblmessage.setBounds(20, 15, 350, 25);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblmessage;
    // End of variables declaration//GEN-END:variables
    
}
